name = "JuliaSub"
uuid = "7a8e1ac7-1981-4f50-b715-6a5b66e1820b"
authors = ["Julia Belyakova <julbinb@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
